config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'sessions#index'

  get '/auth/:provider/callback', to: 'sessions#create'
  post '/auth/:provider/callback', to: 'sessions#create'

  get 'sessions/destroy'

  resources :todos

  resources :users

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.find_or_create_from_auth_hash(auth_hash)
    User.find_by_provider_and_identifier_on_provider(auth_hash["provider"], auth_hash["uid"]) ||
      User.create_with_omniauth(auth_hash)
  end

  def self.create_with_omniauth(auth_hash)
    create! do |user|
      user.provider = auth_hash["provider"]
      user.identifier_on_provider = auth_hash["uid"]

      user.name = (user.provider == "twitter") ? auth_hash["info"]["nickname"]: auth_hash["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize

  helper_method :current_user

  private
  # ユーザ認証されていない場合、トップページにリダイレクトする
  def authorize
    redirect_to('/') unless current_user
  end

  # キャッシュ、もしくはセッション情報からユーザー情報を取得する
  def current_user
    begin
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound => e
      @current_user = nil
    end
  end

  # キャッシュ、およびセッション情報にユーザー情報を格納する
  def current_user=(user)
    @current_user = user
    session[:user_id] = (user) ? user.id: user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, :verify_authenticity_token

  def index
    redirect_to '/todos' unless current_user.nil?
  end

  def create
    @user = User.find_or_create_from_auth_hash(request.env["omniauth.auth"])
    self.current_user = @user

    redirect_to '/todos', :notice => "Signed in!"
  end

  def destroy
    self.current_user = nil
    redirect_to '/', :notice => "Signed out!"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.where(user_id: current_user.id)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    if @todo.nil? then
      render status: :forbidden, file: '/public/403.html'
    end
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_todo
    @todo = Todo.find_by_id_and_user_id(params[:id], current_user.id)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_params
    params.require(:todo).permit(:content, :done)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :name, :image_url, :email, :access_token)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_global_nav.html.erb
<header class="navbar navbar-static-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#global-nav-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Todo さん</a>
    </div>
    <div id="global-nav-menu" class="navbar-collapse collapse">
      <form class="navbar-form navbar-right" role="form" action="/sessions/destroy">
        <button class="btn btn-link" type="submit">ログアウト</button>
      </form>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="todo">
<head>
  <title>TodoSan</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user then %>
  <%= render 'layouts/global_nav' %>
  <% end %>

  <div class="container" ng-controller="todoCtrl">

    <%= yield %>

  </div>
</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
  <h1>TODO 一覧</h1>

  <div class="loading" ng-show="loading">
    <p style="color: #aaa;">ロード中...</p>
  </div>

  <div class="todo-area" ng-hide="loading">
    <div class="table-responsive" ng-hide="loading">
      <table class="table table-striped table-bordered table-hover">
        <tbody>

          <!-- 新規登録フォーム -->
          <tr class="todo-entry-form">
            <td>
              <div class="input-group">
                <div class="input-group-btn">
                  <span class="btn btn-lg btn-primary">&gt;</span>
                </div>
                <form class="input-group-lg" ng-submit="saveNewTodo($event, newtodo)" >
                  <input type="text" name="newtodo-content" class="form-control" ng-model="newtodo.content" placeholder="新規 TODO 内容" autofocus />
                </form>
                <span class="input-group-btn">
                  <a id="add-new-todo-btn" class="btn btn-lg btn-primary" href="/todos" ng-click="saveNewTodo($event, newtodo)"> 追加 </a>
                </span>
              </div>
            </td>
          </tr>

          <!-- 表示、編集フォーム -->
          <tr class="todo-item" ng-repeat="todo in todos | orderBy:'-id'">
            <td>
              <!-- 表示時 -->
              <div ng-hide="todo.editing">
                <div class="pull-left">
                  <input class="btn btn-lg btn-default" type="checkbox" ng-model="todo.done" ng-change="doneEditTodo($event, todo)" />
                </div>
                <span class="pull-right">
                  <a class="btn btn-lg btn-default" ng-click="removeTodo($event, todo)" href="/todos/{{ todo.id }}" rel="nofollow">
                    <span class="glyphicon glyphicon-trash"></span>
                  </a>
                </span>
                <div class="todo-content" ng-class="{ done: todo.done }" ng-click="editTodo($event, todo)">
                  {{todo.content}}
                </div>
              </div>

              <!-- 編集時 -->
              <div class="input-group" ng-show="todo.editing">
                <div class="input-group-btn">
                  <input class="btn btn-lg btn-default glyph-icon disabled" type="checkbox" ng-model="todo.done" />
                </div>
                <form class="input-group-lg" ng-submit="doneEditTodo($event, todo)" >
                  <input type="text" class="form-control" ng-model="todo.content" placeholder="TODO 内容" todo-focus="todo.editing" />
                </form>
                <span class="input-group-btn">
                  <a class="btn btn-lg btn-primary" href="/todos" ng-click="doneEditTodo($event, todo)">変更</a>
                </span>
              </div>

            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @todo.content %>
</p>

<p>
  <strong>Done:</strong>
  <%= @todo.done %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Name</th>
      <th>Image url</th>
      <th>Email</th>
      <th>Access token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.provider %></td>
        <td><%= user.name %></td>
        <td><%= user.image_url %></td>
        <td><%= user.email %></td>
        <td><%= user.access_token %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @user.image_url %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Access token:</strong>
  <%= @user.access_token %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>